version: '3.9'

volumes:
  postgres_data:
  keycloak_data:
  mongodb_data:

services:

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
  
  products_service:
    build:
      context: ./backend/products
    ports:
      - ${PORT_PRODUCTS}:${PORT_PRODUCTS}
    depends_on:
      - mongodb
      - kafka
    environment:
      - MONGODB_URI_PRODUCTS=${MONGODB_URI_PRODUCTS}
      - PORT_PRODUCTS=${PORT_PRODUCTS}
      
  orders_service:
   build:
     context: ./backend/orders
   ports:
    - ${PORT_ORDERS}:${PORT_ORDERS}
   depends_on:
    - mongodb
    - kafka
   environment:
    - MONGODB_URI_ORDERS=${MONGODB_URI_ORDERS}
    - PORT_ORDERS=${PORT_ORDERS}

  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password

  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      WAIT_FOR: postgres:5432
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    restart: unless-stopped
    
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
    - default

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka
    ports:
      - "8097:8097"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:8097,INTERNAL://kafka:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    networks:
      - default
    restart: on-failure
    healthcheck:
        test: ["CMD", "ping", "-c","1", "localhost:8097"]
        interval: 30s
        timeout: 10s
        retries: 5

  control-center:
      image: confluentinc/cp-enterprise-control-center:latest
      hostname: control-center
      depends_on:
        - kafka
      ports:
        - "9021:9021"
      expose:
        - 9021
      environment:
        CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:19092'
        CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        CONTROL_CENTER_REPLICATION_FACTOR: 1
        PORT: 9021
      networks:
      - default
      restart: always