version: '3.9'

volumes:
  postgres_data:
  keycloak_data:
  mongodb_data:

services:

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
  
  products_service:
    build:
      context: ./backend/products
    ports:
      - ${PORT_PRODUCTS}:${PORT_PRODUCTS}
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI_PRODUCTS=${MONGODB_URI_PRODUCTS}
      - PORT_PRODUCTS=${PORT_PRODUCTS}
      
  orders_service:
   build:
     context: ./backend/orders
   ports:
    - ${PORT_ORDERS}:${PORT_ORDERS}
   depends_on:
    - mongodb
   environment:
    - MONGODB_URI_ORDERS=${MONGODB_URI_ORDERS}
    - PORT_ORDERS=${PORT_ORDERS}

  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password

  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      WAIT_FOR: postgres:5432
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    restart: unless-stopped
    